// Code generated by procgen.go.

#include <proc.h>

PFN_vkCreateInstance createInstance = NULL;
PFN_vkDestroyInstance destroyInstance = NULL;
PFN_vkEnumeratePhysicalDevices enumeratePhysicalDevices = NULL;
PFN_vkGetDeviceProcAddr getDeviceProcAddr = NULL;
PFN_vkGetInstanceProcAddr getInstanceProcAddr = NULL;
PFN_vkGetPhysicalDeviceProperties getPhysicalDeviceProperties = NULL;
PFN_vkGetPhysicalDeviceQueueFamilyProperties getPhysicalDeviceQueueFamilyProperties = NULL;
PFN_vkGetPhysicalDeviceMemoryProperties getPhysicalDeviceMemoryProperties = NULL;
PFN_vkGetPhysicalDeviceFeatures getPhysicalDeviceFeatures = NULL;
PFN_vkGetPhysicalDeviceFormatProperties getPhysicalDeviceFormatProperties = NULL;
PFN_vkGetPhysicalDeviceImageFormatProperties getPhysicalDeviceImageFormatProperties = NULL;
PFN_vkCreateDevice createDevice = NULL;
PFN_vkDestroyDevice destroyDevice = NULL;
PFN_vkEnumerateInstanceVersion enumerateInstanceVersion = NULL;
PFN_vkEnumerateInstanceLayerProperties enumerateInstanceLayerProperties = NULL;
PFN_vkEnumerateInstanceExtensionProperties enumerateInstanceExtensionProperties = NULL;
PFN_vkEnumerateDeviceLayerProperties enumerateDeviceLayerProperties = NULL;
PFN_vkEnumerateDeviceExtensionProperties enumerateDeviceExtensionProperties = NULL;
PFN_vkGetDeviceQueue getDeviceQueue = NULL;
PFN_vkQueueSubmit queueSubmit = NULL;
PFN_vkQueueWaitIdle queueWaitIdle = NULL;
PFN_vkDeviceWaitIdle deviceWaitIdle = NULL;
PFN_vkAllocateMemory allocateMemory = NULL;
PFN_vkFreeMemory freeMemory = NULL;
PFN_vkMapMemory mapMemory = NULL;
PFN_vkUnmapMemory unmapMemory = NULL;
PFN_vkFlushMappedMemoryRanges flushMappedMemoryRanges = NULL;
PFN_vkInvalidateMappedMemoryRanges invalidateMappedMemoryRanges = NULL;
PFN_vkGetDeviceMemoryCommitment getDeviceMemoryCommitment = NULL;
PFN_vkGetBufferMemoryRequirements getBufferMemoryRequirements = NULL;
PFN_vkBindBufferMemory bindBufferMemory = NULL;
PFN_vkGetImageMemoryRequirements getImageMemoryRequirements = NULL;
PFN_vkBindImageMemory bindImageMemory = NULL;
PFN_vkGetImageSparseMemoryRequirements getImageSparseMemoryRequirements = NULL;
PFN_vkGetPhysicalDeviceSparseImageFormatProperties getPhysicalDeviceSparseImageFormatProperties = NULL;
PFN_vkQueueBindSparse queueBindSparse = NULL;
PFN_vkCreateFence createFence = NULL;
PFN_vkDestroyFence destroyFence = NULL;
PFN_vkResetFences resetFences = NULL;
PFN_vkGetFenceStatus getFenceStatus = NULL;
PFN_vkWaitForFences waitForFences = NULL;
PFN_vkCreateSemaphore createSemaphore = NULL;
PFN_vkDestroySemaphore destroySemaphore = NULL;
PFN_vkCreateEvent createEvent = NULL;
PFN_vkDestroyEvent destroyEvent = NULL;
PFN_vkGetEventStatus getEventStatus = NULL;
PFN_vkSetEvent setEvent = NULL;
PFN_vkResetEvent resetEvent = NULL;
PFN_vkCreateQueryPool createQueryPool = NULL;
PFN_vkDestroyQueryPool destroyQueryPool = NULL;
PFN_vkGetQueryPoolResults getQueryPoolResults = NULL;
PFN_vkResetQueryPool resetQueryPool = NULL;
PFN_vkCreateBuffer createBuffer = NULL;
PFN_vkDestroyBuffer destroyBuffer = NULL;
PFN_vkCreateBufferView createBufferView = NULL;
PFN_vkDestroyBufferView destroyBufferView = NULL;
PFN_vkCreateImage createImage = NULL;
PFN_vkDestroyImage destroyImage = NULL;
PFN_vkGetImageSubresourceLayout getImageSubresourceLayout = NULL;
PFN_vkCreateImageView createImageView = NULL;
PFN_vkDestroyImageView destroyImageView = NULL;
PFN_vkCreateShaderModule createShaderModule = NULL;
PFN_vkDestroyShaderModule destroyShaderModule = NULL;
PFN_vkCreatePipelineCache createPipelineCache = NULL;
PFN_vkDestroyPipelineCache destroyPipelineCache = NULL;
PFN_vkGetPipelineCacheData getPipelineCacheData = NULL;
PFN_vkMergePipelineCaches mergePipelineCaches = NULL;
PFN_vkCreateGraphicsPipelines createGraphicsPipelines = NULL;
PFN_vkCreateComputePipelines createComputePipelines = NULL;
PFN_vkDestroyPipeline destroyPipeline = NULL;
PFN_vkCreatePipelineLayout createPipelineLayout = NULL;
PFN_vkDestroyPipelineLayout destroyPipelineLayout = NULL;
PFN_vkCreateSampler createSampler = NULL;
PFN_vkDestroySampler destroySampler = NULL;
PFN_vkCreateDescriptorSetLayout createDescriptorSetLayout = NULL;
PFN_vkDestroyDescriptorSetLayout destroyDescriptorSetLayout = NULL;
PFN_vkCreateDescriptorPool createDescriptorPool = NULL;
PFN_vkDestroyDescriptorPool destroyDescriptorPool = NULL;
PFN_vkResetDescriptorPool resetDescriptorPool = NULL;
PFN_vkAllocateDescriptorSets allocateDescriptorSets = NULL;
PFN_vkFreeDescriptorSets freeDescriptorSets = NULL;
PFN_vkUpdateDescriptorSets updateDescriptorSets = NULL;
PFN_vkCreateFramebuffer createFramebuffer = NULL;
PFN_vkDestroyFramebuffer destroyFramebuffer = NULL;
PFN_vkCreateRenderPass createRenderPass = NULL;
PFN_vkDestroyRenderPass destroyRenderPass = NULL;
PFN_vkGetRenderAreaGranularity getRenderAreaGranularity = NULL;
PFN_vkCreateCommandPool createCommandPool = NULL;
PFN_vkDestroyCommandPool destroyCommandPool = NULL;
PFN_vkResetCommandPool resetCommandPool = NULL;
PFN_vkAllocateCommandBuffers allocateCommandBuffers = NULL;
PFN_vkFreeCommandBuffers freeCommandBuffers = NULL;
PFN_vkBeginCommandBuffer beginCommandBuffer = NULL;
PFN_vkEndCommandBuffer endCommandBuffer = NULL;
PFN_vkResetCommandBuffer resetCommandBuffer = NULL;
PFN_vkCmdBindPipeline cmdBindPipeline = NULL;
PFN_vkCmdSetViewport cmdSetViewport = NULL;
PFN_vkCmdSetScissor cmdSetScissor = NULL;
PFN_vkCmdSetLineWidth cmdSetLineWidth = NULL;
PFN_vkCmdSetDepthBias cmdSetDepthBias = NULL;
PFN_vkCmdSetBlendConstants cmdSetBlendConstants = NULL;
PFN_vkCmdSetDepthBounds cmdSetDepthBounds = NULL;
PFN_vkCmdSetStencilCompareMask cmdSetStencilCompareMask = NULL;
PFN_vkCmdSetStencilWriteMask cmdSetStencilWriteMask = NULL;
PFN_vkCmdSetStencilReference cmdSetStencilReference = NULL;
PFN_vkCmdBindDescriptorSets cmdBindDescriptorSets = NULL;
PFN_vkCmdBindIndexBuffer cmdBindIndexBuffer = NULL;
PFN_vkCmdBindVertexBuffers cmdBindVertexBuffers = NULL;
PFN_vkCmdDraw cmdDraw = NULL;
PFN_vkCmdDrawIndexed cmdDrawIndexed = NULL;
PFN_vkCmdDrawIndirect cmdDrawIndirect = NULL;
PFN_vkCmdDrawIndexedIndirect cmdDrawIndexedIndirect = NULL;
PFN_vkCmdDispatch cmdDispatch = NULL;
PFN_vkCmdDispatchIndirect cmdDispatchIndirect = NULL;
PFN_vkCmdCopyBuffer cmdCopyBuffer = NULL;
PFN_vkCmdCopyImage cmdCopyImage = NULL;
PFN_vkCmdBlitImage cmdBlitImage = NULL;
PFN_vkCmdCopyBufferToImage cmdCopyBufferToImage = NULL;
PFN_vkCmdCopyImageToBuffer cmdCopyImageToBuffer = NULL;
PFN_vkCmdUpdateBuffer cmdUpdateBuffer = NULL;
PFN_vkCmdFillBuffer cmdFillBuffer = NULL;
PFN_vkCmdClearColorImage cmdClearColorImage = NULL;
PFN_vkCmdClearDepthStencilImage cmdClearDepthStencilImage = NULL;
PFN_vkCmdClearAttachments cmdClearAttachments = NULL;
PFN_vkCmdResolveImage cmdResolveImage = NULL;
PFN_vkCmdSetEvent cmdSetEvent = NULL;
PFN_vkCmdResetEvent cmdResetEvent = NULL;
PFN_vkCmdWaitEvents cmdWaitEvents = NULL;
PFN_vkCmdPipelineBarrier cmdPipelineBarrier = NULL;
PFN_vkCmdBeginQuery cmdBeginQuery = NULL;
PFN_vkCmdEndQuery cmdEndQuery = NULL;
PFN_vkCmdResetQueryPool cmdResetQueryPool = NULL;
PFN_vkCmdWriteTimestamp cmdWriteTimestamp = NULL;
PFN_vkCmdCopyQueryPoolResults cmdCopyQueryPoolResults = NULL;
PFN_vkCmdPushConstants cmdPushConstants = NULL;
PFN_vkCmdBeginRenderPass cmdBeginRenderPass = NULL;
PFN_vkCmdNextSubpass cmdNextSubpass = NULL;
PFN_vkCmdEndRenderPass cmdEndRenderPass = NULL;
PFN_vkCmdExecuteCommands cmdExecuteCommands = NULL;
#ifdef __ANDROID__
PFN_vkCreateAndroidSurfaceKHR createAndroidSurfaceKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkGetPhysicalDeviceDisplayPropertiesKHR getPhysicalDeviceDisplayPropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR getPhysicalDeviceDisplayPlanePropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkGetDisplayPlaneSupportedDisplaysKHR getDisplayPlaneSupportedDisplaysKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkGetDisplayModePropertiesKHR getDisplayModePropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkCreateDisplayModeKHR createDisplayModeKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkGetDisplayPlaneCapabilitiesKHR getDisplayPlaneCapabilitiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkCreateDisplayPlaneSurfaceKHR createDisplayPlaneSurfaceKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
PFN_vkCreateSharedSwapchainsKHR createSharedSwapchainsKHR = NULL;
#endif
PFN_vkDestroySurfaceKHR destroySurfaceKHR = NULL;
PFN_vkGetPhysicalDeviceSurfaceSupportKHR getPhysicalDeviceSurfaceSupportKHR = NULL;
PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR getPhysicalDeviceSurfaceCapabilitiesKHR = NULL;
PFN_vkGetPhysicalDeviceSurfaceFormatsKHR getPhysicalDeviceSurfaceFormatsKHR = NULL;
PFN_vkGetPhysicalDeviceSurfacePresentModesKHR getPhysicalDeviceSurfacePresentModesKHR = NULL;
PFN_vkCreateSwapchainKHR createSwapchainKHR = NULL;
PFN_vkDestroySwapchainKHR destroySwapchainKHR = NULL;
PFN_vkGetSwapchainImagesKHR getSwapchainImagesKHR = NULL;
PFN_vkAcquireNextImageKHR acquireNextImageKHR = NULL;
PFN_vkQueuePresentKHR queuePresentKHR = NULL;
#ifdef __linux__
PFN_vkCreateWaylandSurfaceKHR createWaylandSurfaceKHR = NULL;
#endif
#ifdef __linux__
PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR getPhysicalDeviceWaylandPresentationSupportKHR = NULL;
#endif
#ifdef _WIN32
PFN_vkCreateWin32SurfaceKHR createWin32SurfaceKHR = NULL;
#endif
#ifdef _WIN32
PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR getPhysicalDeviceWin32PresentationSupportKHR = NULL;
#endif
#ifdef __linux__
PFN_vkCreateXcbSurfaceKHR createXcbSurfaceKHR = NULL;
#endif
#ifdef __linux__
PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR getPhysicalDeviceXcbPresentationSupportKHR = NULL;
#endif
PFN_vkGetPhysicalDeviceFeatures2 getPhysicalDeviceFeatures2 = NULL;
PFN_vkGetPhysicalDeviceProperties2 getPhysicalDeviceProperties2 = NULL;
PFN_vkGetPhysicalDeviceFormatProperties2 getPhysicalDeviceFormatProperties2 = NULL;
PFN_vkGetPhysicalDeviceImageFormatProperties2 getPhysicalDeviceImageFormatProperties2 = NULL;
PFN_vkGetPhysicalDeviceQueueFamilyProperties2 getPhysicalDeviceQueueFamilyProperties2 = NULL;
PFN_vkGetPhysicalDeviceMemoryProperties2 getPhysicalDeviceMemoryProperties2 = NULL;
PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 getPhysicalDeviceSparseImageFormatProperties2 = NULL;
PFN_vkTrimCommandPool trimCommandPool = NULL;
PFN_vkGetPhysicalDeviceExternalBufferProperties getPhysicalDeviceExternalBufferProperties = NULL;
PFN_vkGetPhysicalDeviceExternalSemaphoreProperties getPhysicalDeviceExternalSemaphoreProperties = NULL;
PFN_vkGetPhysicalDeviceExternalFenceProperties getPhysicalDeviceExternalFenceProperties = NULL;
PFN_vkEnumeratePhysicalDeviceGroups enumeratePhysicalDeviceGroups = NULL;
PFN_vkGetDeviceGroupPeerMemoryFeatures getDeviceGroupPeerMemoryFeatures = NULL;
PFN_vkBindBufferMemory2 bindBufferMemory2 = NULL;
PFN_vkBindImageMemory2 bindImageMemory2 = NULL;
PFN_vkCmdSetDeviceMask cmdSetDeviceMask = NULL;
PFN_vkCmdDispatchBase cmdDispatchBase = NULL;
PFN_vkCreateDescriptorUpdateTemplate createDescriptorUpdateTemplate = NULL;
PFN_vkDestroyDescriptorUpdateTemplate destroyDescriptorUpdateTemplate = NULL;
PFN_vkUpdateDescriptorSetWithTemplate updateDescriptorSetWithTemplate = NULL;
PFN_vkGetBufferMemoryRequirements2 getBufferMemoryRequirements2 = NULL;
PFN_vkGetImageMemoryRequirements2 getImageMemoryRequirements2 = NULL;
PFN_vkGetImageSparseMemoryRequirements2 getImageSparseMemoryRequirements2 = NULL;
PFN_vkGetDeviceBufferMemoryRequirements getDeviceBufferMemoryRequirements = NULL;
PFN_vkGetDeviceImageMemoryRequirements getDeviceImageMemoryRequirements = NULL;
PFN_vkGetDeviceImageSparseMemoryRequirements getDeviceImageSparseMemoryRequirements = NULL;
PFN_vkCreateSamplerYcbcrConversion createSamplerYcbcrConversion = NULL;
PFN_vkDestroySamplerYcbcrConversion destroySamplerYcbcrConversion = NULL;
PFN_vkGetDeviceQueue2 getDeviceQueue2 = NULL;
PFN_vkGetDescriptorSetLayoutSupport getDescriptorSetLayoutSupport = NULL;
PFN_vkCreateRenderPass2 createRenderPass2 = NULL;
PFN_vkCmdBeginRenderPass2 cmdBeginRenderPass2 = NULL;
PFN_vkCmdNextSubpass2 cmdNextSubpass2 = NULL;
PFN_vkCmdEndRenderPass2 cmdEndRenderPass2 = NULL;
PFN_vkGetSemaphoreCounterValue getSemaphoreCounterValue = NULL;
PFN_vkWaitSemaphores waitSemaphores = NULL;
PFN_vkSignalSemaphore signalSemaphore = NULL;
PFN_vkCmdDrawIndirectCount cmdDrawIndirectCount = NULL;
PFN_vkCmdDrawIndexedIndirectCount cmdDrawIndexedIndirectCount = NULL;
PFN_vkGetBufferOpaqueCaptureAddress getBufferOpaqueCaptureAddress = NULL;
PFN_vkGetBufferDeviceAddress getBufferDeviceAddress = NULL;
PFN_vkGetDeviceMemoryOpaqueCaptureAddress getDeviceMemoryOpaqueCaptureAddress = NULL;
PFN_vkGetPhysicalDeviceToolProperties getPhysicalDeviceToolProperties = NULL;
PFN_vkCmdSetCullMode cmdSetCullMode = NULL;
PFN_vkCmdSetFrontFace cmdSetFrontFace = NULL;
PFN_vkCmdSetPrimitiveTopology cmdSetPrimitiveTopology = NULL;
PFN_vkCmdSetViewportWithCount cmdSetViewportWithCount = NULL;
PFN_vkCmdSetScissorWithCount cmdSetScissorWithCount = NULL;
PFN_vkCmdBindVertexBuffers2 cmdBindVertexBuffers2 = NULL;
PFN_vkCmdSetDepthTestEnable cmdSetDepthTestEnable = NULL;
PFN_vkCmdSetDepthWriteEnable cmdSetDepthWriteEnable = NULL;
PFN_vkCmdSetDepthCompareOp cmdSetDepthCompareOp = NULL;
PFN_vkCmdSetDepthBoundsTestEnable cmdSetDepthBoundsTestEnable = NULL;
PFN_vkCmdSetStencilTestEnable cmdSetStencilTestEnable = NULL;
PFN_vkCmdSetStencilOp cmdSetStencilOp = NULL;
PFN_vkCmdSetRasterizerDiscardEnable cmdSetRasterizerDiscardEnable = NULL;
PFN_vkCmdSetDepthBiasEnable cmdSetDepthBiasEnable = NULL;
PFN_vkCmdSetPrimitiveRestartEnable cmdSetPrimitiveRestartEnable = NULL;
PFN_vkCreatePrivateDataSlot createPrivateDataSlot = NULL;
PFN_vkDestroyPrivateDataSlot destroyPrivateDataSlot = NULL;
PFN_vkSetPrivateData setPrivateData = NULL;
PFN_vkGetPrivateData getPrivateData = NULL;
PFN_vkCmdCopyBuffer2 cmdCopyBuffer2 = NULL;
PFN_vkCmdCopyImage2 cmdCopyImage2 = NULL;
PFN_vkCmdBlitImage2 cmdBlitImage2 = NULL;
PFN_vkCmdCopyBufferToImage2 cmdCopyBufferToImage2 = NULL;
PFN_vkCmdCopyImageToBuffer2 cmdCopyImageToBuffer2 = NULL;
PFN_vkCmdResolveImage2 cmdResolveImage2 = NULL;
PFN_vkCmdSetEvent2 cmdSetEvent2 = NULL;
PFN_vkCmdResetEvent2 cmdResetEvent2 = NULL;
PFN_vkCmdWaitEvents2 cmdWaitEvents2 = NULL;
PFN_vkCmdPipelineBarrier2 cmdPipelineBarrier2 = NULL;
PFN_vkQueueSubmit2 queueSubmit2 = NULL;
PFN_vkCmdWriteTimestamp2 cmdWriteTimestamp2 = NULL;
PFN_vkCmdBeginRendering cmdBeginRendering = NULL;
PFN_vkCmdEndRendering cmdEndRendering = NULL;

void getGlobalProcs(void) {
	PFN_vkVoidFunction fp = NULL;
	fp = getInstanceProcAddr(NULL, "vkCreateInstance");
	createInstance = (PFN_vkCreateInstance)fp;
	fp = getInstanceProcAddr(NULL, "vkEnumerateInstanceVersion");
	enumerateInstanceVersion = (PFN_vkEnumerateInstanceVersion)fp;
	fp = getInstanceProcAddr(NULL, "vkEnumerateInstanceLayerProperties");
	enumerateInstanceLayerProperties = (PFN_vkEnumerateInstanceLayerProperties)fp;
	fp = getInstanceProcAddr(NULL, "vkEnumerateInstanceExtensionProperties");
	enumerateInstanceExtensionProperties = (PFN_vkEnumerateInstanceExtensionProperties)fp;
}

void getInstanceProcs(VkInstance dh) {
	PFN_vkVoidFunction fp = NULL;
	fp = getInstanceProcAddr(dh, "vkDestroyInstance");
	destroyInstance = (PFN_vkDestroyInstance)fp;
	fp = getInstanceProcAddr(dh, "vkEnumeratePhysicalDevices");
	enumeratePhysicalDevices = (PFN_vkEnumeratePhysicalDevices)fp;
	fp = getInstanceProcAddr(dh, "vkGetDeviceProcAddr");
	getDeviceProcAddr = (PFN_vkGetDeviceProcAddr)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceProperties");
	getPhysicalDeviceProperties = (PFN_vkGetPhysicalDeviceProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceQueueFamilyProperties");
	getPhysicalDeviceQueueFamilyProperties = (PFN_vkGetPhysicalDeviceQueueFamilyProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceMemoryProperties");
	getPhysicalDeviceMemoryProperties = (PFN_vkGetPhysicalDeviceMemoryProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceFeatures");
	getPhysicalDeviceFeatures = (PFN_vkGetPhysicalDeviceFeatures)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceFormatProperties");
	getPhysicalDeviceFormatProperties = (PFN_vkGetPhysicalDeviceFormatProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceImageFormatProperties");
	getPhysicalDeviceImageFormatProperties = (PFN_vkGetPhysicalDeviceImageFormatProperties)fp;
	fp = getInstanceProcAddr(dh, "vkCreateDevice");
	createDevice = (PFN_vkCreateDevice)fp;
	fp = getInstanceProcAddr(dh, "vkEnumerateDeviceLayerProperties");
	enumerateDeviceLayerProperties = (PFN_vkEnumerateDeviceLayerProperties)fp;
	fp = getInstanceProcAddr(dh, "vkEnumerateDeviceExtensionProperties");
	enumerateDeviceExtensionProperties = (PFN_vkEnumerateDeviceExtensionProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSparseImageFormatProperties");
	getPhysicalDeviceSparseImageFormatProperties = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties)fp;
#ifdef __ANDROID__
	fp = getInstanceProcAddr(dh, "vkCreateAndroidSurfaceKHR");
	createAndroidSurfaceKHR = (PFN_vkCreateAndroidSurfaceKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceDisplayPropertiesKHR");
	getPhysicalDeviceDisplayPropertiesKHR = (PFN_vkGetPhysicalDeviceDisplayPropertiesKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceDisplayPlanePropertiesKHR");
	getPhysicalDeviceDisplayPlanePropertiesKHR = (PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkGetDisplayPlaneSupportedDisplaysKHR");
	getDisplayPlaneSupportedDisplaysKHR = (PFN_vkGetDisplayPlaneSupportedDisplaysKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkGetDisplayModePropertiesKHR");
	getDisplayModePropertiesKHR = (PFN_vkGetDisplayModePropertiesKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkCreateDisplayModeKHR");
	createDisplayModeKHR = (PFN_vkCreateDisplayModeKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkGetDisplayPlaneCapabilitiesKHR");
	getDisplayPlaneCapabilitiesKHR = (PFN_vkGetDisplayPlaneCapabilitiesKHR)fp;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getInstanceProcAddr(dh, "vkCreateDisplayPlaneSurfaceKHR");
	createDisplayPlaneSurfaceKHR = (PFN_vkCreateDisplayPlaneSurfaceKHR)fp;
#endif
	fp = getInstanceProcAddr(dh, "vkDestroySurfaceKHR");
	destroySurfaceKHR = (PFN_vkDestroySurfaceKHR)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSurfaceSupportKHR");
	getPhysicalDeviceSurfaceSupportKHR = (PFN_vkGetPhysicalDeviceSurfaceSupportKHR)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR");
	getPhysicalDeviceSurfaceCapabilitiesKHR = (PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSurfaceFormatsKHR");
	getPhysicalDeviceSurfaceFormatsKHR = (PFN_vkGetPhysicalDeviceSurfaceFormatsKHR)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSurfacePresentModesKHR");
	getPhysicalDeviceSurfacePresentModesKHR = (PFN_vkGetPhysicalDeviceSurfacePresentModesKHR)fp;
#ifdef __linux__
	fp = getInstanceProcAddr(dh, "vkCreateWaylandSurfaceKHR");
	createWaylandSurfaceKHR = (PFN_vkCreateWaylandSurfaceKHR)fp;
#endif
#ifdef __linux__
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceWaylandPresentationSupportKHR");
	getPhysicalDeviceWaylandPresentationSupportKHR = (PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR)fp;
#endif
#ifdef _WIN32
	fp = getInstanceProcAddr(dh, "vkCreateWin32SurfaceKHR");
	createWin32SurfaceKHR = (PFN_vkCreateWin32SurfaceKHR)fp;
#endif
#ifdef _WIN32
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceWin32PresentationSupportKHR");
	getPhysicalDeviceWin32PresentationSupportKHR = (PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR)fp;
#endif
#ifdef __linux__
	fp = getInstanceProcAddr(dh, "vkCreateXcbSurfaceKHR");
	createXcbSurfaceKHR = (PFN_vkCreateXcbSurfaceKHR)fp;
#endif
#ifdef __linux__
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceXcbPresentationSupportKHR");
	getPhysicalDeviceXcbPresentationSupportKHR = (PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR)fp;
#endif
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceFeatures2");
	getPhysicalDeviceFeatures2 = (PFN_vkGetPhysicalDeviceFeatures2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceProperties2");
	getPhysicalDeviceProperties2 = (PFN_vkGetPhysicalDeviceProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceFormatProperties2");
	getPhysicalDeviceFormatProperties2 = (PFN_vkGetPhysicalDeviceFormatProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceImageFormatProperties2");
	getPhysicalDeviceImageFormatProperties2 = (PFN_vkGetPhysicalDeviceImageFormatProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceQueueFamilyProperties2");
	getPhysicalDeviceQueueFamilyProperties2 = (PFN_vkGetPhysicalDeviceQueueFamilyProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceMemoryProperties2");
	getPhysicalDeviceMemoryProperties2 = (PFN_vkGetPhysicalDeviceMemoryProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceSparseImageFormatProperties2");
	getPhysicalDeviceSparseImageFormatProperties2 = (PFN_vkGetPhysicalDeviceSparseImageFormatProperties2)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceExternalBufferProperties");
	getPhysicalDeviceExternalBufferProperties = (PFN_vkGetPhysicalDeviceExternalBufferProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceExternalSemaphoreProperties");
	getPhysicalDeviceExternalSemaphoreProperties = (PFN_vkGetPhysicalDeviceExternalSemaphoreProperties)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceExternalFenceProperties");
	getPhysicalDeviceExternalFenceProperties = (PFN_vkGetPhysicalDeviceExternalFenceProperties)fp;
	fp = getInstanceProcAddr(dh, "vkEnumeratePhysicalDeviceGroups");
	enumeratePhysicalDeviceGroups = (PFN_vkEnumeratePhysicalDeviceGroups)fp;
	fp = getInstanceProcAddr(dh, "vkGetPhysicalDeviceToolProperties");
	getPhysicalDeviceToolProperties = (PFN_vkGetPhysicalDeviceToolProperties)fp;
}

void getDeviceProcs(VkDevice dh) {
	PFN_vkVoidFunction fp = NULL;
	fp = getDeviceProcAddr(dh, "vkDestroyDevice");
	destroyDevice = (PFN_vkDestroyDevice)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceQueue");
	getDeviceQueue = (PFN_vkGetDeviceQueue)fp;
	fp = getDeviceProcAddr(dh, "vkQueueSubmit");
	queueSubmit = (PFN_vkQueueSubmit)fp;
	fp = getDeviceProcAddr(dh, "vkQueueWaitIdle");
	queueWaitIdle = (PFN_vkQueueWaitIdle)fp;
	fp = getDeviceProcAddr(dh, "vkDeviceWaitIdle");
	deviceWaitIdle = (PFN_vkDeviceWaitIdle)fp;
	fp = getDeviceProcAddr(dh, "vkAllocateMemory");
	allocateMemory = (PFN_vkAllocateMemory)fp;
	fp = getDeviceProcAddr(dh, "vkFreeMemory");
	freeMemory = (PFN_vkFreeMemory)fp;
	fp = getDeviceProcAddr(dh, "vkMapMemory");
	mapMemory = (PFN_vkMapMemory)fp;
	fp = getDeviceProcAddr(dh, "vkUnmapMemory");
	unmapMemory = (PFN_vkUnmapMemory)fp;
	fp = getDeviceProcAddr(dh, "vkFlushMappedMemoryRanges");
	flushMappedMemoryRanges = (PFN_vkFlushMappedMemoryRanges)fp;
	fp = getDeviceProcAddr(dh, "vkInvalidateMappedMemoryRanges");
	invalidateMappedMemoryRanges = (PFN_vkInvalidateMappedMemoryRanges)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceMemoryCommitment");
	getDeviceMemoryCommitment = (PFN_vkGetDeviceMemoryCommitment)fp;
	fp = getDeviceProcAddr(dh, "vkGetBufferMemoryRequirements");
	getBufferMemoryRequirements = (PFN_vkGetBufferMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkBindBufferMemory");
	bindBufferMemory = (PFN_vkBindBufferMemory)fp;
	fp = getDeviceProcAddr(dh, "vkGetImageMemoryRequirements");
	getImageMemoryRequirements = (PFN_vkGetImageMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkBindImageMemory");
	bindImageMemory = (PFN_vkBindImageMemory)fp;
	fp = getDeviceProcAddr(dh, "vkGetImageSparseMemoryRequirements");
	getImageSparseMemoryRequirements = (PFN_vkGetImageSparseMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkQueueBindSparse");
	queueBindSparse = (PFN_vkQueueBindSparse)fp;
	fp = getDeviceProcAddr(dh, "vkCreateFence");
	createFence = (PFN_vkCreateFence)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyFence");
	destroyFence = (PFN_vkDestroyFence)fp;
	fp = getDeviceProcAddr(dh, "vkResetFences");
	resetFences = (PFN_vkResetFences)fp;
	fp = getDeviceProcAddr(dh, "vkGetFenceStatus");
	getFenceStatus = (PFN_vkGetFenceStatus)fp;
	fp = getDeviceProcAddr(dh, "vkWaitForFences");
	waitForFences = (PFN_vkWaitForFences)fp;
	fp = getDeviceProcAddr(dh, "vkCreateSemaphore");
	createSemaphore = (PFN_vkCreateSemaphore)fp;
	fp = getDeviceProcAddr(dh, "vkDestroySemaphore");
	destroySemaphore = (PFN_vkDestroySemaphore)fp;
	fp = getDeviceProcAddr(dh, "vkCreateEvent");
	createEvent = (PFN_vkCreateEvent)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyEvent");
	destroyEvent = (PFN_vkDestroyEvent)fp;
	fp = getDeviceProcAddr(dh, "vkGetEventStatus");
	getEventStatus = (PFN_vkGetEventStatus)fp;
	fp = getDeviceProcAddr(dh, "vkSetEvent");
	setEvent = (PFN_vkSetEvent)fp;
	fp = getDeviceProcAddr(dh, "vkResetEvent");
	resetEvent = (PFN_vkResetEvent)fp;
	fp = getDeviceProcAddr(dh, "vkCreateQueryPool");
	createQueryPool = (PFN_vkCreateQueryPool)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyQueryPool");
	destroyQueryPool = (PFN_vkDestroyQueryPool)fp;
	fp = getDeviceProcAddr(dh, "vkGetQueryPoolResults");
	getQueryPoolResults = (PFN_vkGetQueryPoolResults)fp;
	fp = getDeviceProcAddr(dh, "vkResetQueryPool");
	resetQueryPool = (PFN_vkResetQueryPool)fp;
	fp = getDeviceProcAddr(dh, "vkCreateBuffer");
	createBuffer = (PFN_vkCreateBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyBuffer");
	destroyBuffer = (PFN_vkDestroyBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCreateBufferView");
	createBufferView = (PFN_vkCreateBufferView)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyBufferView");
	destroyBufferView = (PFN_vkDestroyBufferView)fp;
	fp = getDeviceProcAddr(dh, "vkCreateImage");
	createImage = (PFN_vkCreateImage)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyImage");
	destroyImage = (PFN_vkDestroyImage)fp;
	fp = getDeviceProcAddr(dh, "vkGetImageSubresourceLayout");
	getImageSubresourceLayout = (PFN_vkGetImageSubresourceLayout)fp;
	fp = getDeviceProcAddr(dh, "vkCreateImageView");
	createImageView = (PFN_vkCreateImageView)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyImageView");
	destroyImageView = (PFN_vkDestroyImageView)fp;
	fp = getDeviceProcAddr(dh, "vkCreateShaderModule");
	createShaderModule = (PFN_vkCreateShaderModule)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyShaderModule");
	destroyShaderModule = (PFN_vkDestroyShaderModule)fp;
	fp = getDeviceProcAddr(dh, "vkCreatePipelineCache");
	createPipelineCache = (PFN_vkCreatePipelineCache)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyPipelineCache");
	destroyPipelineCache = (PFN_vkDestroyPipelineCache)fp;
	fp = getDeviceProcAddr(dh, "vkGetPipelineCacheData");
	getPipelineCacheData = (PFN_vkGetPipelineCacheData)fp;
	fp = getDeviceProcAddr(dh, "vkMergePipelineCaches");
	mergePipelineCaches = (PFN_vkMergePipelineCaches)fp;
	fp = getDeviceProcAddr(dh, "vkCreateGraphicsPipelines");
	createGraphicsPipelines = (PFN_vkCreateGraphicsPipelines)fp;
	fp = getDeviceProcAddr(dh, "vkCreateComputePipelines");
	createComputePipelines = (PFN_vkCreateComputePipelines)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyPipeline");
	destroyPipeline = (PFN_vkDestroyPipeline)fp;
	fp = getDeviceProcAddr(dh, "vkCreatePipelineLayout");
	createPipelineLayout = (PFN_vkCreatePipelineLayout)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyPipelineLayout");
	destroyPipelineLayout = (PFN_vkDestroyPipelineLayout)fp;
	fp = getDeviceProcAddr(dh, "vkCreateSampler");
	createSampler = (PFN_vkCreateSampler)fp;
	fp = getDeviceProcAddr(dh, "vkDestroySampler");
	destroySampler = (PFN_vkDestroySampler)fp;
	fp = getDeviceProcAddr(dh, "vkCreateDescriptorSetLayout");
	createDescriptorSetLayout = (PFN_vkCreateDescriptorSetLayout)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyDescriptorSetLayout");
	destroyDescriptorSetLayout = (PFN_vkDestroyDescriptorSetLayout)fp;
	fp = getDeviceProcAddr(dh, "vkCreateDescriptorPool");
	createDescriptorPool = (PFN_vkCreateDescriptorPool)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyDescriptorPool");
	destroyDescriptorPool = (PFN_vkDestroyDescriptorPool)fp;
	fp = getDeviceProcAddr(dh, "vkResetDescriptorPool");
	resetDescriptorPool = (PFN_vkResetDescriptorPool)fp;
	fp = getDeviceProcAddr(dh, "vkAllocateDescriptorSets");
	allocateDescriptorSets = (PFN_vkAllocateDescriptorSets)fp;
	fp = getDeviceProcAddr(dh, "vkFreeDescriptorSets");
	freeDescriptorSets = (PFN_vkFreeDescriptorSets)fp;
	fp = getDeviceProcAddr(dh, "vkUpdateDescriptorSets");
	updateDescriptorSets = (PFN_vkUpdateDescriptorSets)fp;
	fp = getDeviceProcAddr(dh, "vkCreateFramebuffer");
	createFramebuffer = (PFN_vkCreateFramebuffer)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyFramebuffer");
	destroyFramebuffer = (PFN_vkDestroyFramebuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCreateRenderPass");
	createRenderPass = (PFN_vkCreateRenderPass)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyRenderPass");
	destroyRenderPass = (PFN_vkDestroyRenderPass)fp;
	fp = getDeviceProcAddr(dh, "vkGetRenderAreaGranularity");
	getRenderAreaGranularity = (PFN_vkGetRenderAreaGranularity)fp;
	fp = getDeviceProcAddr(dh, "vkCreateCommandPool");
	createCommandPool = (PFN_vkCreateCommandPool)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyCommandPool");
	destroyCommandPool = (PFN_vkDestroyCommandPool)fp;
	fp = getDeviceProcAddr(dh, "vkResetCommandPool");
	resetCommandPool = (PFN_vkResetCommandPool)fp;
	fp = getDeviceProcAddr(dh, "vkAllocateCommandBuffers");
	allocateCommandBuffers = (PFN_vkAllocateCommandBuffers)fp;
	fp = getDeviceProcAddr(dh, "vkFreeCommandBuffers");
	freeCommandBuffers = (PFN_vkFreeCommandBuffers)fp;
	fp = getDeviceProcAddr(dh, "vkBeginCommandBuffer");
	beginCommandBuffer = (PFN_vkBeginCommandBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkEndCommandBuffer");
	endCommandBuffer = (PFN_vkEndCommandBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkResetCommandBuffer");
	resetCommandBuffer = (PFN_vkResetCommandBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBindPipeline");
	cmdBindPipeline = (PFN_vkCmdBindPipeline)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetViewport");
	cmdSetViewport = (PFN_vkCmdSetViewport)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetScissor");
	cmdSetScissor = (PFN_vkCmdSetScissor)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetLineWidth");
	cmdSetLineWidth = (PFN_vkCmdSetLineWidth)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthBias");
	cmdSetDepthBias = (PFN_vkCmdSetDepthBias)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetBlendConstants");
	cmdSetBlendConstants = (PFN_vkCmdSetBlendConstants)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthBounds");
	cmdSetDepthBounds = (PFN_vkCmdSetDepthBounds)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetStencilCompareMask");
	cmdSetStencilCompareMask = (PFN_vkCmdSetStencilCompareMask)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetStencilWriteMask");
	cmdSetStencilWriteMask = (PFN_vkCmdSetStencilWriteMask)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetStencilReference");
	cmdSetStencilReference = (PFN_vkCmdSetStencilReference)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBindDescriptorSets");
	cmdBindDescriptorSets = (PFN_vkCmdBindDescriptorSets)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBindIndexBuffer");
	cmdBindIndexBuffer = (PFN_vkCmdBindIndexBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBindVertexBuffers");
	cmdBindVertexBuffers = (PFN_vkCmdBindVertexBuffers)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDraw");
	cmdDraw = (PFN_vkCmdDraw)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDrawIndexed");
	cmdDrawIndexed = (PFN_vkCmdDrawIndexed)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDrawIndirect");
	cmdDrawIndirect = (PFN_vkCmdDrawIndirect)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDrawIndexedIndirect");
	cmdDrawIndexedIndirect = (PFN_vkCmdDrawIndexedIndirect)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDispatch");
	cmdDispatch = (PFN_vkCmdDispatch)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDispatchIndirect");
	cmdDispatchIndirect = (PFN_vkCmdDispatchIndirect)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyBuffer");
	cmdCopyBuffer = (PFN_vkCmdCopyBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyImage");
	cmdCopyImage = (PFN_vkCmdCopyImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBlitImage");
	cmdBlitImage = (PFN_vkCmdBlitImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyBufferToImage");
	cmdCopyBufferToImage = (PFN_vkCmdCopyBufferToImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyImageToBuffer");
	cmdCopyImageToBuffer = (PFN_vkCmdCopyImageToBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdUpdateBuffer");
	cmdUpdateBuffer = (PFN_vkCmdUpdateBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdFillBuffer");
	cmdFillBuffer = (PFN_vkCmdFillBuffer)fp;
	fp = getDeviceProcAddr(dh, "vkCmdClearColorImage");
	cmdClearColorImage = (PFN_vkCmdClearColorImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdClearDepthStencilImage");
	cmdClearDepthStencilImage = (PFN_vkCmdClearDepthStencilImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdClearAttachments");
	cmdClearAttachments = (PFN_vkCmdClearAttachments)fp;
	fp = getDeviceProcAddr(dh, "vkCmdResolveImage");
	cmdResolveImage = (PFN_vkCmdResolveImage)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetEvent");
	cmdSetEvent = (PFN_vkCmdSetEvent)fp;
	fp = getDeviceProcAddr(dh, "vkCmdResetEvent");
	cmdResetEvent = (PFN_vkCmdResetEvent)fp;
	fp = getDeviceProcAddr(dh, "vkCmdWaitEvents");
	cmdWaitEvents = (PFN_vkCmdWaitEvents)fp;
	fp = getDeviceProcAddr(dh, "vkCmdPipelineBarrier");
	cmdPipelineBarrier = (PFN_vkCmdPipelineBarrier)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBeginQuery");
	cmdBeginQuery = (PFN_vkCmdBeginQuery)fp;
	fp = getDeviceProcAddr(dh, "vkCmdEndQuery");
	cmdEndQuery = (PFN_vkCmdEndQuery)fp;
	fp = getDeviceProcAddr(dh, "vkCmdResetQueryPool");
	cmdResetQueryPool = (PFN_vkCmdResetQueryPool)fp;
	fp = getDeviceProcAddr(dh, "vkCmdWriteTimestamp");
	cmdWriteTimestamp = (PFN_vkCmdWriteTimestamp)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyQueryPoolResults");
	cmdCopyQueryPoolResults = (PFN_vkCmdCopyQueryPoolResults)fp;
	fp = getDeviceProcAddr(dh, "vkCmdPushConstants");
	cmdPushConstants = (PFN_vkCmdPushConstants)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBeginRenderPass");
	cmdBeginRenderPass = (PFN_vkCmdBeginRenderPass)fp;
	fp = getDeviceProcAddr(dh, "vkCmdNextSubpass");
	cmdNextSubpass = (PFN_vkCmdNextSubpass)fp;
	fp = getDeviceProcAddr(dh, "vkCmdEndRenderPass");
	cmdEndRenderPass = (PFN_vkCmdEndRenderPass)fp;
	fp = getDeviceProcAddr(dh, "vkCmdExecuteCommands");
	cmdExecuteCommands = (PFN_vkCmdExecuteCommands)fp;
#if !defined(__ANDROID__) && !defined(_WIN32)
	fp = getDeviceProcAddr(dh, "vkCreateSharedSwapchainsKHR");
	createSharedSwapchainsKHR = (PFN_vkCreateSharedSwapchainsKHR)fp;
#endif
	fp = getDeviceProcAddr(dh, "vkCreateSwapchainKHR");
	createSwapchainKHR = (PFN_vkCreateSwapchainKHR)fp;
	fp = getDeviceProcAddr(dh, "vkDestroySwapchainKHR");
	destroySwapchainKHR = (PFN_vkDestroySwapchainKHR)fp;
	fp = getDeviceProcAddr(dh, "vkGetSwapchainImagesKHR");
	getSwapchainImagesKHR = (PFN_vkGetSwapchainImagesKHR)fp;
	fp = getDeviceProcAddr(dh, "vkAcquireNextImageKHR");
	acquireNextImageKHR = (PFN_vkAcquireNextImageKHR)fp;
	fp = getDeviceProcAddr(dh, "vkQueuePresentKHR");
	queuePresentKHR = (PFN_vkQueuePresentKHR)fp;
	fp = getDeviceProcAddr(dh, "vkTrimCommandPool");
	trimCommandPool = (PFN_vkTrimCommandPool)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceGroupPeerMemoryFeatures");
	getDeviceGroupPeerMemoryFeatures = (PFN_vkGetDeviceGroupPeerMemoryFeatures)fp;
	fp = getDeviceProcAddr(dh, "vkBindBufferMemory2");
	bindBufferMemory2 = (PFN_vkBindBufferMemory2)fp;
	fp = getDeviceProcAddr(dh, "vkBindImageMemory2");
	bindImageMemory2 = (PFN_vkBindImageMemory2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDeviceMask");
	cmdSetDeviceMask = (PFN_vkCmdSetDeviceMask)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDispatchBase");
	cmdDispatchBase = (PFN_vkCmdDispatchBase)fp;
	fp = getDeviceProcAddr(dh, "vkCreateDescriptorUpdateTemplate");
	createDescriptorUpdateTemplate = (PFN_vkCreateDescriptorUpdateTemplate)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyDescriptorUpdateTemplate");
	destroyDescriptorUpdateTemplate = (PFN_vkDestroyDescriptorUpdateTemplate)fp;
	fp = getDeviceProcAddr(dh, "vkUpdateDescriptorSetWithTemplate");
	updateDescriptorSetWithTemplate = (PFN_vkUpdateDescriptorSetWithTemplate)fp;
	fp = getDeviceProcAddr(dh, "vkGetBufferMemoryRequirements2");
	getBufferMemoryRequirements2 = (PFN_vkGetBufferMemoryRequirements2)fp;
	fp = getDeviceProcAddr(dh, "vkGetImageMemoryRequirements2");
	getImageMemoryRequirements2 = (PFN_vkGetImageMemoryRequirements2)fp;
	fp = getDeviceProcAddr(dh, "vkGetImageSparseMemoryRequirements2");
	getImageSparseMemoryRequirements2 = (PFN_vkGetImageSparseMemoryRequirements2)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceBufferMemoryRequirements");
	getDeviceBufferMemoryRequirements = (PFN_vkGetDeviceBufferMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceImageMemoryRequirements");
	getDeviceImageMemoryRequirements = (PFN_vkGetDeviceImageMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceImageSparseMemoryRequirements");
	getDeviceImageSparseMemoryRequirements = (PFN_vkGetDeviceImageSparseMemoryRequirements)fp;
	fp = getDeviceProcAddr(dh, "vkCreateSamplerYcbcrConversion");
	createSamplerYcbcrConversion = (PFN_vkCreateSamplerYcbcrConversion)fp;
	fp = getDeviceProcAddr(dh, "vkDestroySamplerYcbcrConversion");
	destroySamplerYcbcrConversion = (PFN_vkDestroySamplerYcbcrConversion)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceQueue2");
	getDeviceQueue2 = (PFN_vkGetDeviceQueue2)fp;
	fp = getDeviceProcAddr(dh, "vkGetDescriptorSetLayoutSupport");
	getDescriptorSetLayoutSupport = (PFN_vkGetDescriptorSetLayoutSupport)fp;
	fp = getDeviceProcAddr(dh, "vkCreateRenderPass2");
	createRenderPass2 = (PFN_vkCreateRenderPass2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBeginRenderPass2");
	cmdBeginRenderPass2 = (PFN_vkCmdBeginRenderPass2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdNextSubpass2");
	cmdNextSubpass2 = (PFN_vkCmdNextSubpass2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdEndRenderPass2");
	cmdEndRenderPass2 = (PFN_vkCmdEndRenderPass2)fp;
	fp = getDeviceProcAddr(dh, "vkGetSemaphoreCounterValue");
	getSemaphoreCounterValue = (PFN_vkGetSemaphoreCounterValue)fp;
	fp = getDeviceProcAddr(dh, "vkWaitSemaphores");
	waitSemaphores = (PFN_vkWaitSemaphores)fp;
	fp = getDeviceProcAddr(dh, "vkSignalSemaphore");
	signalSemaphore = (PFN_vkSignalSemaphore)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDrawIndirectCount");
	cmdDrawIndirectCount = (PFN_vkCmdDrawIndirectCount)fp;
	fp = getDeviceProcAddr(dh, "vkCmdDrawIndexedIndirectCount");
	cmdDrawIndexedIndirectCount = (PFN_vkCmdDrawIndexedIndirectCount)fp;
	fp = getDeviceProcAddr(dh, "vkGetBufferOpaqueCaptureAddress");
	getBufferOpaqueCaptureAddress = (PFN_vkGetBufferOpaqueCaptureAddress)fp;
	fp = getDeviceProcAddr(dh, "vkGetBufferDeviceAddress");
	getBufferDeviceAddress = (PFN_vkGetBufferDeviceAddress)fp;
	fp = getDeviceProcAddr(dh, "vkGetDeviceMemoryOpaqueCaptureAddress");
	getDeviceMemoryOpaqueCaptureAddress = (PFN_vkGetDeviceMemoryOpaqueCaptureAddress)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetCullMode");
	cmdSetCullMode = (PFN_vkCmdSetCullMode)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetFrontFace");
	cmdSetFrontFace = (PFN_vkCmdSetFrontFace)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetPrimitiveTopology");
	cmdSetPrimitiveTopology = (PFN_vkCmdSetPrimitiveTopology)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetViewportWithCount");
	cmdSetViewportWithCount = (PFN_vkCmdSetViewportWithCount)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetScissorWithCount");
	cmdSetScissorWithCount = (PFN_vkCmdSetScissorWithCount)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBindVertexBuffers2");
	cmdBindVertexBuffers2 = (PFN_vkCmdBindVertexBuffers2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthTestEnable");
	cmdSetDepthTestEnable = (PFN_vkCmdSetDepthTestEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthWriteEnable");
	cmdSetDepthWriteEnable = (PFN_vkCmdSetDepthWriteEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthCompareOp");
	cmdSetDepthCompareOp = (PFN_vkCmdSetDepthCompareOp)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthBoundsTestEnable");
	cmdSetDepthBoundsTestEnable = (PFN_vkCmdSetDepthBoundsTestEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetStencilTestEnable");
	cmdSetStencilTestEnable = (PFN_vkCmdSetStencilTestEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetStencilOp");
	cmdSetStencilOp = (PFN_vkCmdSetStencilOp)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetRasterizerDiscardEnable");
	cmdSetRasterizerDiscardEnable = (PFN_vkCmdSetRasterizerDiscardEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetDepthBiasEnable");
	cmdSetDepthBiasEnable = (PFN_vkCmdSetDepthBiasEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetPrimitiveRestartEnable");
	cmdSetPrimitiveRestartEnable = (PFN_vkCmdSetPrimitiveRestartEnable)fp;
	fp = getDeviceProcAddr(dh, "vkCreatePrivateDataSlot");
	createPrivateDataSlot = (PFN_vkCreatePrivateDataSlot)fp;
	fp = getDeviceProcAddr(dh, "vkDestroyPrivateDataSlot");
	destroyPrivateDataSlot = (PFN_vkDestroyPrivateDataSlot)fp;
	fp = getDeviceProcAddr(dh, "vkSetPrivateData");
	setPrivateData = (PFN_vkSetPrivateData)fp;
	fp = getDeviceProcAddr(dh, "vkGetPrivateData");
	getPrivateData = (PFN_vkGetPrivateData)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyBuffer2");
	cmdCopyBuffer2 = (PFN_vkCmdCopyBuffer2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyImage2");
	cmdCopyImage2 = (PFN_vkCmdCopyImage2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBlitImage2");
	cmdBlitImage2 = (PFN_vkCmdBlitImage2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyBufferToImage2");
	cmdCopyBufferToImage2 = (PFN_vkCmdCopyBufferToImage2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdCopyImageToBuffer2");
	cmdCopyImageToBuffer2 = (PFN_vkCmdCopyImageToBuffer2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdResolveImage2");
	cmdResolveImage2 = (PFN_vkCmdResolveImage2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdSetEvent2");
	cmdSetEvent2 = (PFN_vkCmdSetEvent2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdResetEvent2");
	cmdResetEvent2 = (PFN_vkCmdResetEvent2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdWaitEvents2");
	cmdWaitEvents2 = (PFN_vkCmdWaitEvents2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdPipelineBarrier2");
	cmdPipelineBarrier2 = (PFN_vkCmdPipelineBarrier2)fp;
	fp = getDeviceProcAddr(dh, "vkQueueSubmit2");
	queueSubmit2 = (PFN_vkQueueSubmit2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdWriteTimestamp2");
	cmdWriteTimestamp2 = (PFN_vkCmdWriteTimestamp2)fp;
	fp = getDeviceProcAddr(dh, "vkCmdBeginRendering");
	cmdBeginRendering = (PFN_vkCmdBeginRendering)fp;
	fp = getDeviceProcAddr(dh, "vkCmdEndRendering");
	cmdEndRendering = (PFN_vkCmdEndRendering)fp;
}

void clearProcs(void) {
	createInstance = NULL;
	destroyInstance = NULL;
	enumeratePhysicalDevices = NULL;
	getDeviceProcAddr = NULL;
	getPhysicalDeviceProperties = NULL;
	getPhysicalDeviceQueueFamilyProperties = NULL;
	getPhysicalDeviceMemoryProperties = NULL;
	getPhysicalDeviceFeatures = NULL;
	getPhysicalDeviceFormatProperties = NULL;
	getPhysicalDeviceImageFormatProperties = NULL;
	createDevice = NULL;
	destroyDevice = NULL;
	enumerateInstanceVersion = NULL;
	enumerateInstanceLayerProperties = NULL;
	enumerateInstanceExtensionProperties = NULL;
	enumerateDeviceLayerProperties = NULL;
	enumerateDeviceExtensionProperties = NULL;
	getDeviceQueue = NULL;
	queueSubmit = NULL;
	queueWaitIdle = NULL;
	deviceWaitIdle = NULL;
	allocateMemory = NULL;
	freeMemory = NULL;
	mapMemory = NULL;
	unmapMemory = NULL;
	flushMappedMemoryRanges = NULL;
	invalidateMappedMemoryRanges = NULL;
	getDeviceMemoryCommitment = NULL;
	getBufferMemoryRequirements = NULL;
	bindBufferMemory = NULL;
	getImageMemoryRequirements = NULL;
	bindImageMemory = NULL;
	getImageSparseMemoryRequirements = NULL;
	getPhysicalDeviceSparseImageFormatProperties = NULL;
	queueBindSparse = NULL;
	createFence = NULL;
	destroyFence = NULL;
	resetFences = NULL;
	getFenceStatus = NULL;
	waitForFences = NULL;
	createSemaphore = NULL;
	destroySemaphore = NULL;
	createEvent = NULL;
	destroyEvent = NULL;
	getEventStatus = NULL;
	setEvent = NULL;
	resetEvent = NULL;
	createQueryPool = NULL;
	destroyQueryPool = NULL;
	getQueryPoolResults = NULL;
	resetQueryPool = NULL;
	createBuffer = NULL;
	destroyBuffer = NULL;
	createBufferView = NULL;
	destroyBufferView = NULL;
	createImage = NULL;
	destroyImage = NULL;
	getImageSubresourceLayout = NULL;
	createImageView = NULL;
	destroyImageView = NULL;
	createShaderModule = NULL;
	destroyShaderModule = NULL;
	createPipelineCache = NULL;
	destroyPipelineCache = NULL;
	getPipelineCacheData = NULL;
	mergePipelineCaches = NULL;
	createGraphicsPipelines = NULL;
	createComputePipelines = NULL;
	destroyPipeline = NULL;
	createPipelineLayout = NULL;
	destroyPipelineLayout = NULL;
	createSampler = NULL;
	destroySampler = NULL;
	createDescriptorSetLayout = NULL;
	destroyDescriptorSetLayout = NULL;
	createDescriptorPool = NULL;
	destroyDescriptorPool = NULL;
	resetDescriptorPool = NULL;
	allocateDescriptorSets = NULL;
	freeDescriptorSets = NULL;
	updateDescriptorSets = NULL;
	createFramebuffer = NULL;
	destroyFramebuffer = NULL;
	createRenderPass = NULL;
	destroyRenderPass = NULL;
	getRenderAreaGranularity = NULL;
	createCommandPool = NULL;
	destroyCommandPool = NULL;
	resetCommandPool = NULL;
	allocateCommandBuffers = NULL;
	freeCommandBuffers = NULL;
	beginCommandBuffer = NULL;
	endCommandBuffer = NULL;
	resetCommandBuffer = NULL;
	cmdBindPipeline = NULL;
	cmdSetViewport = NULL;
	cmdSetScissor = NULL;
	cmdSetLineWidth = NULL;
	cmdSetDepthBias = NULL;
	cmdSetBlendConstants = NULL;
	cmdSetDepthBounds = NULL;
	cmdSetStencilCompareMask = NULL;
	cmdSetStencilWriteMask = NULL;
	cmdSetStencilReference = NULL;
	cmdBindDescriptorSets = NULL;
	cmdBindIndexBuffer = NULL;
	cmdBindVertexBuffers = NULL;
	cmdDraw = NULL;
	cmdDrawIndexed = NULL;
	cmdDrawIndirect = NULL;
	cmdDrawIndexedIndirect = NULL;
	cmdDispatch = NULL;
	cmdDispatchIndirect = NULL;
	cmdCopyBuffer = NULL;
	cmdCopyImage = NULL;
	cmdBlitImage = NULL;
	cmdCopyBufferToImage = NULL;
	cmdCopyImageToBuffer = NULL;
	cmdUpdateBuffer = NULL;
	cmdFillBuffer = NULL;
	cmdClearColorImage = NULL;
	cmdClearDepthStencilImage = NULL;
	cmdClearAttachments = NULL;
	cmdResolveImage = NULL;
	cmdSetEvent = NULL;
	cmdResetEvent = NULL;
	cmdWaitEvents = NULL;
	cmdPipelineBarrier = NULL;
	cmdBeginQuery = NULL;
	cmdEndQuery = NULL;
	cmdResetQueryPool = NULL;
	cmdWriteTimestamp = NULL;
	cmdCopyQueryPoolResults = NULL;
	cmdPushConstants = NULL;
	cmdBeginRenderPass = NULL;
	cmdNextSubpass = NULL;
	cmdEndRenderPass = NULL;
	cmdExecuteCommands = NULL;
#ifdef __ANDROID__
	createAndroidSurfaceKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	getPhysicalDeviceDisplayPropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	getPhysicalDeviceDisplayPlanePropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	getDisplayPlaneSupportedDisplaysKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	getDisplayModePropertiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	createDisplayModeKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	getDisplayPlaneCapabilitiesKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	createDisplayPlaneSurfaceKHR = NULL;
#endif
#if !defined(__ANDROID__) && !defined(_WIN32)
	createSharedSwapchainsKHR = NULL;
#endif
	destroySurfaceKHR = NULL;
	getPhysicalDeviceSurfaceSupportKHR = NULL;
	getPhysicalDeviceSurfaceCapabilitiesKHR = NULL;
	getPhysicalDeviceSurfaceFormatsKHR = NULL;
	getPhysicalDeviceSurfacePresentModesKHR = NULL;
	createSwapchainKHR = NULL;
	destroySwapchainKHR = NULL;
	getSwapchainImagesKHR = NULL;
	acquireNextImageKHR = NULL;
	queuePresentKHR = NULL;
#ifdef __linux__
	createWaylandSurfaceKHR = NULL;
#endif
#ifdef __linux__
	getPhysicalDeviceWaylandPresentationSupportKHR = NULL;
#endif
#ifdef _WIN32
	createWin32SurfaceKHR = NULL;
#endif
#ifdef _WIN32
	getPhysicalDeviceWin32PresentationSupportKHR = NULL;
#endif
#ifdef __linux__
	createXcbSurfaceKHR = NULL;
#endif
#ifdef __linux__
	getPhysicalDeviceXcbPresentationSupportKHR = NULL;
#endif
	getPhysicalDeviceFeatures2 = NULL;
	getPhysicalDeviceProperties2 = NULL;
	getPhysicalDeviceFormatProperties2 = NULL;
	getPhysicalDeviceImageFormatProperties2 = NULL;
	getPhysicalDeviceQueueFamilyProperties2 = NULL;
	getPhysicalDeviceMemoryProperties2 = NULL;
	getPhysicalDeviceSparseImageFormatProperties2 = NULL;
	trimCommandPool = NULL;
	getPhysicalDeviceExternalBufferProperties = NULL;
	getPhysicalDeviceExternalSemaphoreProperties = NULL;
	getPhysicalDeviceExternalFenceProperties = NULL;
	enumeratePhysicalDeviceGroups = NULL;
	getDeviceGroupPeerMemoryFeatures = NULL;
	bindBufferMemory2 = NULL;
	bindImageMemory2 = NULL;
	cmdSetDeviceMask = NULL;
	cmdDispatchBase = NULL;
	createDescriptorUpdateTemplate = NULL;
	destroyDescriptorUpdateTemplate = NULL;
	updateDescriptorSetWithTemplate = NULL;
	getBufferMemoryRequirements2 = NULL;
	getImageMemoryRequirements2 = NULL;
	getImageSparseMemoryRequirements2 = NULL;
	getDeviceBufferMemoryRequirements = NULL;
	getDeviceImageMemoryRequirements = NULL;
	getDeviceImageSparseMemoryRequirements = NULL;
	createSamplerYcbcrConversion = NULL;
	destroySamplerYcbcrConversion = NULL;
	getDeviceQueue2 = NULL;
	getDescriptorSetLayoutSupport = NULL;
	createRenderPass2 = NULL;
	cmdBeginRenderPass2 = NULL;
	cmdNextSubpass2 = NULL;
	cmdEndRenderPass2 = NULL;
	getSemaphoreCounterValue = NULL;
	waitSemaphores = NULL;
	signalSemaphore = NULL;
	cmdDrawIndirectCount = NULL;
	cmdDrawIndexedIndirectCount = NULL;
	getBufferOpaqueCaptureAddress = NULL;
	getBufferDeviceAddress = NULL;
	getDeviceMemoryOpaqueCaptureAddress = NULL;
	getPhysicalDeviceToolProperties = NULL;
	cmdSetCullMode = NULL;
	cmdSetFrontFace = NULL;
	cmdSetPrimitiveTopology = NULL;
	cmdSetViewportWithCount = NULL;
	cmdSetScissorWithCount = NULL;
	cmdBindVertexBuffers2 = NULL;
	cmdSetDepthTestEnable = NULL;
	cmdSetDepthWriteEnable = NULL;
	cmdSetDepthCompareOp = NULL;
	cmdSetDepthBoundsTestEnable = NULL;
	cmdSetStencilTestEnable = NULL;
	cmdSetStencilOp = NULL;
	cmdSetRasterizerDiscardEnable = NULL;
	cmdSetDepthBiasEnable = NULL;
	cmdSetPrimitiveRestartEnable = NULL;
	createPrivateDataSlot = NULL;
	destroyPrivateDataSlot = NULL;
	setPrivateData = NULL;
	getPrivateData = NULL;
	cmdCopyBuffer2 = NULL;
	cmdCopyImage2 = NULL;
	cmdBlitImage2 = NULL;
	cmdCopyBufferToImage2 = NULL;
	cmdCopyImageToBuffer2 = NULL;
	cmdResolveImage2 = NULL;
	cmdSetEvent2 = NULL;
	cmdResetEvent2 = NULL;
	cmdWaitEvents2 = NULL;
	cmdPipelineBarrier2 = NULL;
	queueSubmit2 = NULL;
	cmdWriteTimestamp2 = NULL;
	cmdBeginRendering = NULL;
	cmdEndRendering = NULL;
}
